export const initialReleases = [
  {
    id: '1',
    title: 'EDS Status auto sync',
    project: 'UPI',
    em: 'Ashish Agrawal',
    date: '2025-04-08',
    repo: 'UI, Core, UPH',
    status: 'Done',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: '8th April',
    isLastWeek: false
  },
  {
    id: '2',
    title: 'SIDSUM on IDAC Platform',
    project: 'IDAC/SIDSUM',
    em: 'Arvind Ramasarma',
    date: '2025-04-10',
    repo: 'Core, IDAC services',
    status: 'Done',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: 'T3',
    isLastWeek: false
  },
  {
    id: '3',
    title: 'Admin Led Survey',
    project: 'Survey',
    em: 'Ashish Agrawal',
    date: '2025-04-11',
    repo: 'UI, Survey, Notification, Data Gateway',
    status: 'Done',
    priority: 'Medium',
    businessCommitment: true,
    businessCommitmentDate: '11th April',
    isLastWeek: false
  },
  {
    id: '4',
    title: 'UPH Release',
    project: 'M2M',
    em: 'Arvind Ramasarma',
    date: '2025-04-14',
    repo: 'UPH',
    status: 'On Track',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: 'T2',
    isLastWeek: false
  },
  {
    id: '5',
    title: 'CAMI 2.0',
    project: 'M2M',
    em: 'Arvind Ramasarma',
    date: '2025-04-14',
    repo: 'CAMI 2.0',
    status: 'On Track',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: 'T2',
    isLastWeek: false
  },
  {
    id: '6',
    title: 'Tiered Pricing (bug fix)',
    project: 'Tiered Pricing',
    em: 'Puneet Agarwal',
    date: '2025-04-15',
    repo: 'Core',
    status: 'On Track',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: '15 April',
    isLastWeek: false
  },
  {
    id: '7',
    title: 'APH Core Release',
    project: 'M2M',
    em: 'Arvind Ramasarma',
    date: '2025-04-15',
    repo: 'Core',
    status: 'On Track',
    priority: 'Medium',
    businessCommitment: true,
    businessCommitmentDate: 'T2',
    isLastWeek: false
  },
  {
    id: '8',
    title: 'Customer Defects',
    project: 'CUD',
    em: 'Nga Mai Dinh',
    date: '2025-04-15',
    repo: 'Core, Cami, UI',
    status: 'On Track',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: 'T2',
    isLastWeek: false
  },
  {
    id: '9',
    title: 'Alerts',
    project: 'Alerts',
    em: 'Arvind Ramasarma',
    date: '2025-04-15',
    repo: 'Core, UI, Notification',
    status: 'On Track',
    priority: 'Medium',
    businessCommitment: true,
    businessCommitmentDate: 'T2',
    isLastWeek: false
  },
  {
    id: '10',
    title: 'SIDSUM on IDAC Platform',
    project: 'IDAC/SIDSUM',
    em: 'Arvind Ramasarma',
    date: '2025-04-15',
    repo: 'Core, IDAC services',
    status: 'On Track',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: 'T3',
    isLastWeek: false
  },
  {
    id: '11',
    title: 'CAF T2 Drop 3',
    project: 'CAF',
    em: 'Shyam Vasudevan',
    date: '2025-04-17',
    repo: 'cami,cami-forms,configurator',
    status: 'On Track',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: 'T2',
    isLastWeek: false
  },
  {
    id: '12',
    title: 'Infra Release for Slack',
    project: 'Notifications',
    em: 'Pranav Moktali',
    date: '2025-04-17',
    repo: 'Infra Only',
    status: 'On Track',
    priority: 'Low',
    businessCommitment: false,
    businessCommitmentDate: 'T2',
    businessCommitmentJustification: 'Infra required for 24h release',
    isLastWeek: false
  },
  {
    id: '13',
    title: 'Infra Release for Dashboard',
    project: 'Dashboard',
    em: 'Pranav Moktali',
    date: '2025-04-17',
    repo: 'Infra Only',
    status: 'On Track',
    priority: 'Low',
    businessCommitment: false,
    businessCommitmentDate: 'T2',
    businessCommitmentJustification: 'Infra required for 24h release',
    isLastWeek: false
  },
  {
    id: '14',
    title: 'Apps API',
    project: 'Apps API',
    em: 'Sandesh DS',
    date: '2025-04-18',
    repo: 'Core, Core-ext',
    status: 'On Track',
    priority: 'Medium',
    businessCommitment: true,
    businessCommitmentDate: 'T2',
    isLastWeek: false
  },
  {
    id: '15',
    title: 'GTM',
    project: 'GTM',
    em: 'Shyam Vasudevan',
    date: '2025-04-18',
    repo: 'Core, UI',
    status: 'On Track',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: 'T2',
    isLastWeek: false
  },
  {
    id: '16',
    title: 'Infra Release (new container)',
    project: 'Workflows',
    em: 'Puneet Agarwal',
    date: '2025-04-21',
    repo: 'Core',
    status: 'On Track',
    priority: 'Low',
    businessCommitment: false,
    businessCommitmentDate: 'T2',
    isLastWeek: false
  },
  {
    id: '17',
    title: 'DM Framework + Access Review Integration with MS Teams',
    project: 'Notifications',
    em: 'Pranav Moktali',
    date: '2025-04-23',
    repo: 'UI, SIS, Notification, Survey',
    status: 'On Track',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: 'T2',
    businessCommitmentJustification: 'Add MS teams as a notification method for Access Review and EP',
    isLastWeek: false
  },
  {
    id: '18',
    title: 'T2 score card with real data',
    project: 'Dashboard',
    em: 'Pranav Moktali',
    date: '2025-04-23',
    repo: 'UI, microservices',
    status: 'On Track',
    priority: 'Medium',
    businessCommitment: true,
    businessCommitmentDate: 'T2',
    isLastWeek: false
  },
  {
    id: '19',
    title: 'Deleted User profiles',
    project: 'UPI',
    em: 'Ashish Agrawal',
    date: '2025-04-23',
    repo: 'UI, Core, Search service',
    status: 'On Track',
    priority: 'Medium',
    businessCommitment: true,
    businessCommitmentDate: 'T2',
    isLastWeek: false
  },
  {
    id: '20',
    title: 'Support for Delta + New Alerts',
    project: 'Alerts',
    em: 'Arvind Ramasarma',
    date: '2025-04-25',
    repo: 'Core, Alerts Services, Notifications',
    status: 'On Track',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: 'T2',
    isLastWeek: false
  },
  {
    id: '21',
    title: 'GTM',
    project: 'GTM',
    em: 'Shyam Vasudevan',
    date: '2025-04-25',
    repo: 'Core, UI',
    status: 'On Track',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: 'T2',
    isLastWeek: false
  },
  {
    id: '22',
    title: 'Workflows',
    project: 'Workflows',
    em: 'Puneet Agarwal',
    date: '2025-04-28',
    repo: 'core, ui',
    status: 'At Risk',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: 'T2',
    businessCommitmentJustification: 'Must have before T2',
    isLastWeek: true
  },
  {
    id: '23',
    title: 'Slack Interactive Messages',
    project: 'Notifications',
    em: 'Pranav Moktali',
    date: '2025-04-29',
    repo: 'Slack, Notification',
    status: 'At Risk',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: 'T2',
    isLastWeek: true
  },
  {
    id: '24',
    title: 'Scorecard auto-refresh',
    project: 'Dashboard',
    em: 'Pranav Moktali',
    date: '2025-04-29',
    repo: 'MFE + Microservices',
    status: 'At Risk',
    priority: 'Low',
    businessCommitment: false,
    businessCommitmentDate: 'T2',
    businessCommitmentJustification: 'Best effort for auto-refresh in T2',
    isLastWeek: true
  },
  {
    id: '25',
    title: 'EP',
    project: 'EP',
    em: 'Sandesh DS',
    date: '2025-04-29',
    repo: 'Core, UI, EP Services',
    status: 'At Risk',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: 'T2',
    isLastWeek: true
  },
  {
    id: '26',
    title: 'Josy AI initiatives Phase-1',
    project: 'Josy AI initiatives',
    em: 'Kamesh Palani',
    date: '2025-04-30',
    repo: 'JAI, Data Gateway + infra',
    status: 'On Track',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: 'May 5',
    isLastWeek: true
  },
  {
    id: '27',
    title: 'Josy AI initiatives Phase-1',
    project: 'Josy AI initiatives',
    em: 'Kamesh Palani',
    date: '2025-05-05',
    repo: 'UI',
    status: 'On Track',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: 'May 5',
    isLastWeek: false
  },
  {
    id: '28',
    title: 'MFA on MTS Portal',
    project: 'MTS',
    em: 'Pranav Moktali',
    date: '2025-05-06',
    repo: 'MTS',
    status: 'On Track',
    priority: 'High',
    businessCommitment: true,
    businessCommitmentDate: '6 May',
    isLastWeek: false
  }
] as const;